"""Downloads the source corpora and records what was retrieved.

Where each one comes from is set in config/settings.yml under datasets; this
script holds only the fetching, the hashing and the documentation table. A file
already present is left alone, so a rerun costs nothing.

    python scripts/download.py
"""

import hashlib
import io
from datetime import date

import pandas as pd
import requests
from datasets import load_dataset
from settings import (DATASETS, SOURCES_PATH, ORIGINAL_DIR,
                      SAFECHILD_COMMIT)

# ----------------------------------------------------------------------------
# Settings
# ----------------------------------------------------------------------------

TIMEOUT = 60
USER_AGENT = 'thesis-data-collection'

# File-based datasets store only a filename, resolved here against the pinned
# commit so that no url is written out twice.
SAFECHILD_REPOSITORY = ('https://raw.githubusercontent.com/'
                        'The-Responsible-AI-Initiative/Safe_Child_LLM_Evaluation')
SAFECHILD_ASSETS = f'{SAFECHILD_REPOSITORY}/{SAFECHILD_COMMIT}/assets'

# ----------------------------------------------------------------------------
# Functions
# ----------------------------------------------------------------------------

# Define function to fill in the full url of every file-based dataset
def resolve_origins(datasets, assets_url):
    resolved = {}
    for name, spec in datasets.items():
        if spec['kind'] == 'file':
            spec = {**spec, 'origin': f'{assets_url}/{spec["filename"]}'}
        resolved[name] = spec
    return resolved


# Define function to write a file only once it has been read in full
def write_once(frame, path):
    temporary = path.with_suffix('.tmp')
    frame.to_csv(temporary, index=False)
    temporary.replace(path)


# Define function to hash a file so a download can be verified later
def file_hash(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


# Define function to fetch one dataset from the Hugging Face Hub
def fetch_from_hub(spec):
    data = load_dataset(spec['origin'], spec.get('config'), split=spec['split'])
    return data.to_pandas()


# Define function to fetch one dataset from a url, falling back to the archive
def fetch_from_file(spec):
    for url in (spec['origin'], spec.get('fallback')):
        if not url:
            continue
        try:
            response = requests.get(url, timeout=TIMEOUT,
                                    headers={'User-Agent': USER_AGENT})
            response.raise_for_status()
            payload = io.BytesIO(response.content)
            return (pd.read_excel(payload) if spec.get('format') == 'excel'
                    else pd.read_csv(payload))
        except Exception as error:
            print(f'Failed {url.split("/")[2]}, {type(error).__name__}: {error}')
    raise ConnectionError('No source reachable')


# Define function to download one dataset unless it is already present
def download(name, spec, original_dir):
    path = original_dir / f'{name}.csv'
    if path.exists():
        print(f'Skipped {spec["name"]}, already present')
        return True
    try:
        frame = (fetch_from_hub(spec) if spec['kind'] == 'hub'
                 else fetch_from_file(spec))
    except Exception as error:
        print(f'Failed {name}, {type(error).__name__}: {error}')
        return False
    write_once(frame=frame, path=path)
    print(f'Downloaded {spec["name"]}, {len(frame)} rows')
    return True


# Define function to download every dataset and stop if any is missing
def download_all(datasets, original_dir):
    original_dir.mkdir(parents=True, exist_ok=True)
    missing = [name for name, spec in datasets.items()
               if not download(name=name, spec=spec, original_dir=original_dir)]
    if missing:
        raise SystemExit(f'{len(missing)} datasets could not be downloaded: '
                         f'{", ".join(missing)}')


# Define function to record what each downloaded file holds
def summarise_downloads(datasets, original_dir):
    rows = []
    for name, spec in datasets.items():
        path = original_dir / f'{name}.csv'
        rows.append({'dataset': spec['name'], 'origin': spec['origin'],
                     'licence': spec['licence'],
                     'rows': len(pd.read_csv(path)) if path.exists() else 0,
                     'sha256': file_hash(path) if path.exists() else ''})
    downloads = pd.DataFrame(rows)
    print(f'Datasets: {len(downloads)} files, '
          f'{int(downloads["rows"].sum())} source records')
    return downloads


# Define function to write the summary out as the documentation table
def write_documentation(summary, doc_path):
    lines = ['# Datasets', '',
             f'Generated by `scripts/download.py` on {date.today().isoformat()}.',
             'Licences apply to the source datasets and are recorded here only.', '',
             '| Dataset | Origin | Licence | Rows | SHA-256 |',
             '| --- | --- | --- | ---: | --- |']
    for _, row in summary.iterrows():
        present = bool(row['sha256'])
        count = row['rows'] if present else 'missing'
        digest = f"`{row['sha256']}`" if present else ''
        lines.append(f'| {row["dataset"]} | {row["origin"]} | {row["licence"]} | '
                     f'{count} | {digest} |')
    lines += ['', f'pandas {pd.__version__}']
    doc_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Documentation written to {doc_path.name}')


# ----------------------------------------------------------------------------
# Run
# ----------------------------------------------------------------------------

if __name__ == '__main__':
    resolved = resolve_origins(datasets=DATASETS, assets_url=SAFECHILD_ASSETS)
    download_all(datasets=resolved, original_dir=ORIGINAL_DIR)

    downloads = summarise_downloads(datasets=resolved, original_dir=ORIGINAL_DIR)
    write_documentation(summary=downloads, doc_path=SOURCES_PATH)
